### ISSUE TITLE
GHC 7.8.4

### ISSUE THREAD

**Issue by razvan-panda** [octomarat/HaskellDebugger#4]
Does the debugger work with GHC 7.8.4?

I did a local build from 112a3e526e42d82010c22076899a5b617730cdf1 by changing the GHC version to be 7.8.4 in cabal file.

When trying to debug I can step through code but when I evaluate any expressions or add watches the debugger only shows type names:

![](http://i.imgur.com/rChNjmn.png)

Could you provide some tips on how to use the debugger? Thank you

**Comment by razvan-panda** [comment]
When setting the debugger to GHCi the console can be used to evaluate expressions but I could not find any way to do that with remote-debugger yet. In both cases the watches and evaluation windows do not work.

**Comment by Atsky** [comment]
When debuger shows '_' instead value, it means value is lazy and not evaluated yet. You should use "Force evaluation" from context menu. But unfortunately this feature is broken as I can see. (https://github.com/Atsky/haskell-idea-plugin/issues/97)

**Comment by Atsky** [comment]
I have not tested debugger with GHC 7.8.4, but it highly depends on idea version and can be broken.
